apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-bucket
spec:
  refreshinterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  dataFrom:
    - extract:
        key: monitoring-thanos-bucket
