apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-main
  labels:
    app.kubernetes.io/name: postgresql-main
    app.kubernetes.io/instance: postgresql-main
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
  superuserSecret:
    name: cloudnative-pg
  monitoring:
    enablePodMonitor: true

  # TODO: fetch superuser from secret instead of generating
  # TODO: add backup
