apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
    - targetPath: loki.structuredConfig.common.storage.s3.bucketnames
      kind: Secret
      name: loki-bucket
      valuesKey: BUCKET_NAME
    - targetPath: loki.structuredConfig.common.storage.s3.endpoint
      kind: Secret
      name: loki-bucket
      valuesKey: BUCKET_ENDPOINT
    - targetPath: loki.structuredConfig.common.storage.s3.region
      kind: Secret
      name: loki-bucket
      valuesKey: BUCKET_REGION
    - targetPath: loki.structuredConfig.common.storage.s3.access_key_id
      kind: Secret
      name: loki-bucket
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: loki.structuredConfig.common.storage.s3.secret_access_key
      kind: Secret
      name: loki-bucket
      valuesKey: AWS_SECRET_ACCESS_KEY
