loki:
  structuredConfig:
    common:
      ring:
        kvstore:
          store: memberlist
      path_prefix: /var/loki
      storage:
        s3:
          s3forcepathstyle: true
    schema_config:
      configs:
        - from: "2023-01-01"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: index_
            period: 24h
    limits_config:
      retention_period: 30d
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
    ingester:
      max_chunk_age: 1h
    compactor:
      working_directory: /var/loki/boltdb-shipper-compactor
      shared_store: s3
      compaction_interval: 10m
      retention_enabled: true
    analytics:
      reporting_enabled: false
gateway:
  replicas: 1
read:
  replicas: 2
  serviceLabels:
    grafana-agent/collect-metrics: "true"
write:
  replicas: 2
  serviceLabels:
    grafana-agent/collect-metrics: "true"
backend:
  replicas: 2
  serviceLabels:
    grafana-agent/collect-metrics: "true"
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
test:
  enabled: false
