loki:
  structuredConfig:
    auth_enabled: false
    server:
      log_level: info
      http_listen_port: 3100
      grpc_listen_port: 9095
    memberlist:
      join_members: ["loki-memberlist"]
    limits_config:
      retention_period: 14d
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 16
      shard_streams:
        enabled: true
    schema_config:
      configs:
        - from: "2023-01-01"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    common:
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          s3: null
          s3forcepathstyle: true
      ring:
        kvstore:
          store: memberlist
    ruler:
      enable_api: true
      enable_alertmanager_v2: false
      alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
      storage:
        type: local
        local:
          directory: /rules
      rule_path: /tmp/scratch
      ring:
        kvstore:
          store: memberlist
    distributor:
      ring:
        kvstore:
          store: memberlist
    compactor:
      working_directory: /var/loki/boltdb-shipper-compactor
      shared_store: s3
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    ingester:
      max_chunk_age: 1h
      lifecycler:
        ring:
          kvstore:
            store: memberlist
    analytics:
      reporting_enabled: false
gateway:
  replicas: 3
read:
  replicas: 3
  extraVolumeMounts:
    - name: rules
      mountPath: /rules
  extraVolumes:
    - name: rules
      emptyDir: {}
write:
  replicas: 3
backend:
  replicas: 3
  extraVolumes:
    - name: rules
      emptyDir: {}
    - name: scratch
      emptyDir: {}
  extraVolumeMounts:
    - name: rules
      mountPath: /rules/fake
    - name: scratch
      mountPath: /tmp/scratch
monitoring:
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
test:
  enabled: false
