apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.13.2
  interval: 30m

  values:
    bgp:
      enabled: true

    hubble:
      metrics:
        serviceMonitor:
          enabled: true

      relay:
        prometheus:
          serviceMonitor:
            enabled: true

    prometheus:
      serviceMonitor:
        enabled: true

    operator:
      prometheus:
        serviceMonitor:
          enabled: true
