k8sServiceHost: cluster.liveview-template.app
k8sServicePort: 6443
ipam:
  mode: kubernetes
kubeProxyReplacement: strict
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
securityContext:
  privileged: false
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    mountCgroup:
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    applySysctlOverwrites:
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
# ---
autoDirectNodeRoutes: true
endpointRoutes:
  enabled: true
operator:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true
prometheus:
  serviceMonitor:
    enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA,
      - drop
      - tcp
      - flow
      - http
      - icmp
      - port-distribution
    serviceMonitor: true
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    rollOutPods: true
