apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.13.2
      chart: cilium
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
