apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workloads-security-onepassword-connect
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: liveview-template
  path: ./k8s/workloads/security/onepassword-connect
  interval: 15m
  timeout: 5m
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: onepassword-connect
      namespace: security
