apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: onepassword-connect-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
