apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    queryFrontend:
      enabled: true
      replicaCount: 3
    query:
      enabled: true
      replicaCount: 3
      replicaLabel: ["__replica__"]
    dnsDiscovery:
      sidecarsService: kube-prometheus-stack-thanos-discovery
      sidecarsNamespace: monitoring
    bucketweb:
      enabled: true
      replicaCount: 3
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 14d
      retentionResolution1h: 14d
      persistence:
        enabled: true
        size: 10Gi
    storegateway:
      enabled: true
      replicaCount: 3
      persistence:
        enabled: true
        size: 10Gi
    ruler:
      enabled: true
      replicaCount: 3
      replicaLabel: __replica__
      alertmanagers: ["http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        size: 10Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
