apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour-public
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      chart: contour
      version: 11.3.2
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: contour-public-values
