contour:
  manageCRDs: true
  extraArgs:
    - --use-proxy-protocol
  ingressClass:
    name: public
    default: false
envoy:
  useHostPort: false
  service:
    clusterIP: 10.96.0.50
    annotations:
      load-balancer.hetzner.cloud/name: contour-public
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/type: lb11
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
