contour:
  manageCRDs: true
  ingressClass:
    name: public
    default: false
envoy:
  useHostPort: false
  service:
    annotations:
      load-balancer.hetzner.cloud/name: contour-public
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/type: lb11
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
      load-balancer.hetzner.cloud/use-private-ip: "true"
