apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    role: Agent
