image: hexpm/elixir:1.14.3-erlang-25.3-alpine-3.17.2

before_script:
  - mix local.rebar --force
  - mix local.hex --force

deps:
  stage: build
  parallel:
    matrix:
      - MIX_ENV: [dev, test]
  cache:
    - key: deps-$MIX_ENV
      paths:
        - deps/
        - _build/
  artifacts:
    paths:
      - deps/
      - _build/
  script:
    - mix deps.get
    - mix deps.compile

test:
  stage: test
  dependencies:
    - "deps: [test]"
  services:
    - postgres:15.2
  variables:
    MIX_ENV: test
    DB_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - mix test

lint:
  stage: test
  dependencies:
    - "deps: [dev]"
  script:
    - mix format --check-formatted
    - mix credo

analysis:
  stage: test
  dependencies:
    - "deps: [dev]"
  cache:
    - key: analysis
      paths:
        - priv/plts
  script:
    - mix dialyzer
