image: hexpm/elixir:1.14.3-erlang-25.3-alpine-3.17.2

before_script:
  - mix local.rebar --force
  - mix local.hex --force

variables:
  MIX_ENV: test

deps:
  stage: build
  cache:
    - key: deps
      paths:
        - deps/
        - _build/
  artifacts:
    paths:
      - deps/
      - _build/
  script:
    - mix deps.get
    - mix deps.compile

test:
  stage: test
  dependencies:
    - deps
  services:
    - postgres:15.2
  variables:
    DB_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - mix test

lint:
  stage: test
  dependencies:
    - deps
  script:
    - mix format --check-formatted
    - mix credo
