image: hexpm/elixir:1.14.3-erlang-25.3-ubuntu-jammy-20230126

before_script:
  - mix local.rebar --force
  - mix local.hex --force

deps:
  stage: build
  cache:
    - key:
        files:
          - mix.lock
      paths:
        - deps/
        - _build/
  artifacts:
    paths:
      - deps/
      - _build/
  variables:
    MIX_ENV: test
  script:
    - mix deps.get
    - mix deps.compile

test:
  stage: test
  needs:
    - job: deps
      artifacts: true
  services:
    - postgres:15.2
  variables:
    MIX_ENV: test
    DB_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - mix test

lint:
  stage: test
  needs:
    - job: deps
      artifacts: true
  variables:
    MIX_ENV: test
  script:
    - mix format --check-formatted
    - mix credo
