version: '3.7'
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 5s
      interval: 2s
      timeout: 5s
      retries: 20
