version: '3.7'
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432/tcp

  jaeger:
    image: jaegertracing/all-in-one:1.43
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
