services:
  - name: template
    type: web
    plan: starter
    region: frankfurt
    autoDeploy: false
    env: elixir
    buildCommand: mix deploy
    startCommand: _build/prod/rel/template/bin/start
    # domains:
    #   - template.io
    envVars:
      - key: ELIXIR_VERSION
        value: 1.14.4
      - key: ERLANG_VERSION
        value: 25.3
      - key: NAMESPACE
        sync: false
      - key: HONEYCOMB_API_KEY
        sync: false
      - key: CONFIGCAT_SDK_KEY
        sync: false
      - key: HOST
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: LIVEVIEW_SIGNING_SALT
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: POSTMARK_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: template
          property: connectionString

databases:
  - name: template
    plan: starter
    region: frankfurt
    postgresMajorVersion: 15
    user: template
    databaseName: template
