version: "3"

vars:
  INFRA_DIR: "{{.ROOT_DIR}}/infra"
  TALOS_DIR: "{{.INFRA_DIR}}/talos"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/k8s"
  BASE_DOMAIN: liveview-template.app

dotenv: [".env"]

env:
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubeconfig"
  TALOSCONFIG: "{{.TALOS_DIR}}/talosconfig"

includes:
  infra: .taskfiles/infra_tasks.yaml
  k8s: .taskfiles/k8s_tasks.yaml
