version: "3"

vars:
  INFRASTRUCTURE_DIR: "{{.ROOT_DIR}}/infrastructure"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  BASE_DOMAIN: liveview-template.app

dotenv: [".env"]

env:
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubeconfig"

includes:
  infra: .taskfiles/infrastructure_tasks.yaml
  cluster: .taskfiles/cluster_tasks.yaml

tasks:
  init:
    cmds:
      - brew install {{.DEPS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        fluxcd/tap/flux
        go-task/tap/go-task
        kubernetes-cli
        pre-commit
        sops
        terraform
