apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-op
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .DATABASE_USER }}:{{ .DATABASE_PASSWORD }}@{{ .DATABASE_HOST }}:5432/{{ .DATABASE_NAME }}"
        # init-db
        POSTGRES_HOST: "{{ .DATABASE_HOST }}"
        POSTGRES_SUPERUSER: "{{ .SUPERUSER }}"
        POSTGRES_SUPERUSER_PASSWORD: "{{ .SUPERUSER_PASSWORD }}"
        POSTGRES_USER: "{{ .DATABASE_USER }}"
        POSTGRES_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        POSTGRES_DB: "{{ .DATABASE_NAME }}"
  dataFrom:
    - extract:
        key: unleash
    - extract:
        key: postgresql-main
