apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unleash
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: unleash
        namespace: flux-system
      chart: unleash
      version: 2.8.0
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: unleash-values
