apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-op
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      engineVersion: v2
      data:
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: actions-runner-controller
