apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operations
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: actions-runner-controller-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
