apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
spec:
  issuerRef:
    name: selfsigned-issuer
  secretName: ca
  isCA: true
  duration: 2160h
  renewBefore: 360h
  commonName: ca
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca
spec:
  ca:
    secretName: ca
