apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca.liveview-template.app
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed
  commonName: ca.liveview-template.app
  secretName: ca.liveview-template.app
  privateKey:
    algorithm: ECDSA
    size: 256
  isCA: true
  duration: 2160h
  renewBefore: 360h
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca.liveview-template.app
spec:
  ca:
    secretName: ca.liveview-template.app
