apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed
  secretName: ca.liveview-template.app
  commonName: ca.liveview-template.app
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  isCA: true
  duration: 2160h
  renewBefore: 360h
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca.liveview-template.app
spec:
  ca:
    secretName: ca.liveview-template.app
