apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: zalando-postgres-operator
  namespace: flux-system
spec:
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  interval: 1m0s
