env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns
        key: CF_API_TOKEN

provider: cloudflare
extraArgs:
  - --source=ingress

serviceMonitor:
  enabled: true
