env:
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: external-dns
        key: CF_API_KEY
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: external-dns
        key: CF_API_EMAIL

logLevel: debug

provider: cloudflare
extraArgs:
  - --source=ingress

serviceMonitor:
  enabled: true
