apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      engineVersion: v2
      data:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: &host "{{ .GF_DATABASE_HOST }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_USER: &user "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: &pass "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_NAME: &name "{{ .GF_DATABASE_NAME }}"
        # init-db
        POSTGRES_HOST: *host
        POSTGRES_USER: *user
        POSTGRES_PASS: *pass
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: monitoring-grafana-db
    - extract:
        key: default-cloudnative-pg
