apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.21.1
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    role: Aggregator
    replicas: 3
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 0.0.0.0:8686
      sources:
        kubernetes_source:
          type: vector
          version: "2"
          address: 0.0.0.0:6000
      transforms:
        kubernetes_remap:
          type: remap
          inputs: ["kubernetes_source"]
          source: |
            # Standardize 'app' label
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
      sinks:
        kubernetes:
            inputs: ["kubernetes_remap"]
            type: loki
            endpoint: http://loki-gateway.monitoring.svc.cluster.local
            encoding:
              codec: json
            out_of_order_action: accept
            remove_label_fields: true
            remove_timestamp: true
            labels:
              node: |-
                {{ print "'{{ kubernetes.pod_node_name }}'" }}
              app: |-
                {{ print "'{{ custom_app_name }}'" }}
              namespace: |-
                {{ print "'{{ kubernetes.pod_namespace }}'" }}
              pod: |-
                {{ print "'{{ kubernetes.pod_name }}'" }}
              container: |-
                {{ print "'{{ kubernetes.container_name }}'" }}
