apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: vector-aggregator-config
    files:
      - vector.yaml=./config/vector.yaml
configurations:
  - ./kustomizeconfig.yaml
