apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clickhouse-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://docs.altinity.com/clickhouse-operator/
