apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: kube-system
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: clickhouse-operator
        namespace: flux-system
      version: 0.20.3
      chart: altinity-clickhouse-operator
  interval: 30m

  valuesFrom:
    - kind: ConfigMap
      name: clickhouse-operator-values
