apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./helmrelease.yaml

configMapGenerator:
  - name: clickhouse-operator-values
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
