apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./certificate.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: opensearch-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
