ingress:
  enabled: true
  ingressClassName: private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: liveview-template-app.manticore-hippocampus.ts.net
    ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - &host opensearch.liveview-template.app
  tls:
    - secretName: opensearch-tls
      hosts:
        - *host
