global:
  imagePullSecrets:
    - name: dockerconfigjson-github
replicas: 3
extraInitContainers:
  - name: init-db
    image: ghcr.io/cschmatzler/postgresql-initdb:15.2
    imagePullPolicy: Always
    envFrom:
      - secretRef:
          name: grafana-op
persistence:
  enabled: false
testFramework:
  enabled: false
env:
  GF_ANALYTICS_CHECK_FOR_UPDATES: false
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_SSL_MODE: verify-full
  GF_DATABASE_CA_CERT_PATH: /certs/ca.liveview-template.app-bundle.pem
envFromSecrets:
  - name: grafana-op
extraConfigmapMounts:
  - name: ca-bundle
    configMap: ca.liveview-template.app-bundle
    mountPath: /certs
    readOnly: true
admin:
  # These are only applied by Grafana during initial bootstrap - changing them in the
  # secret will not update an existing database.
  existingSecret: grafana-op
  userKey: GRAFANA_ADMIN_USERNAME
  passwordKey: GRAFANA_ADMIN_PASSWORD
resources:
  requests:
    cpu: 16m
    memory: 192M
  limits:
    memory: 192m
ingress:
  enabled: true
  ingressClassName: private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: liveview-template-app.manticore-hippocampus.ts.net
    ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - &host grafana.liveview-template.app
  tls:
    - secretName: grafana-tls
      hosts:
        - *host
