extraInitContainers:
  - name: init-db
    image: ghcr.io/cschmatzler/postgresql-initdb:15.2
    imagePullPolicy: Always
    envFrom:
      - secretRef:
          name: grafana-config
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
  datasources:
    enabled: true
    searchNamespace: ALL

persistence:
  enabled: false
testFramework:
  enabled: false

env:
  GF_ANALYTICS_CHECK_FOR_UPDATES: false
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_SSL_MODE: verify-full
  GF_DATABASE_CA_CERT_PATH: /certs/ca.crt
envFromSecrets:
  - name: grafana-config
extraSecretMounts:
  - name: postgresql-main-tls
    mountPath: /certs
    readOnly: true
    secretName: postgresql-main-tls

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - name: Loki
        orgId: 1
      - name: Alertmanager
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://mimir-query-frontend.monitoring.svc.cluster.local:8080/prometheus
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "liveview-template.app"
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        jsonData:
          maxLines: 250
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "liveview-template.app"
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.monitoring.svc.cluster.local:3100
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "liveview-template.app"
dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 31
      folder: Infra
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kube-state-metrics:
      gnetId: 13332
      revision: 12
      folder: Infra
      datasource: Prometheus
    external-secrets:
      url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
      datasource: Prometheus
    flux-cluster:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/cluster.json
      datasource: Prometheus
    flux-control-plane:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/control-plane.json
      datasource: Prometheus
    flux-logs:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/logs.json
      datasource:
        - name: DS_LOKI
          value: Loki

ingress:
  enabled: true
  ingressClassName: private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: liveview-template-app.manticore-hippocampus.ts.net
    ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - &host grafana.liveview-template.app
  tls:
    - secretName: grafana-tls
      hosts:
        - *host

admin:
  # These are only applied by Grafana during initial bootstrap - changing them in the
  # secret will not update an existing database.
  existingSecret: grafana-config
  userKey: GRAFANA_USERNAME
  passwordKey: GRAFANA_PASSWORD
