apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      chart: kyverno
      version: 3.0.0-beta.1
  interval: 10m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-values
