apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workloads-operations-actions-runner-controller
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: liveview-template
  path: ./k8s/workloads/operations/actions-runner-controller
  interval: 10m
  timeout: 5m
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: actions-runner-controller
      namespace: operations
