apiVersion: v1
kind: Namespace
metadata:
  name: operations
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/enabled: "true"
