apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-main
  labels:
    app.kubernetes.io/name: postgresql-main
    app.kubernetes.io/instance: postgresql-main
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  superuserSecret:
    name: cloudnative-pg
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      # TODO: update this from default to database
      destinationPath: s3://liveview-template-app-default-postgresql-main
      endpointURL: http://s3.eu-central-2.wasabisys.com
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg
          key: aws-secret-access-key
  monitoring:
    enablePodMonitor: true
