apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      chart: tempo-distributed
      version: 1.3.0
  interval: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
    - targetPath: storage.trace.s3.bucket
      kind: Secret
      name: tempo-op
      valuesKey: BUCKET_NAME
    - targetPath: storage.trace.s3.endpoint
      kind: Secret
      name: tempo-op
      valuesKey: BUCKET_ENDPOINT
    - targetPath: storage.trace.s3.region
      kind: Secret
      name: tempo-op
      valuesKey: BUCKET_REGION
    - targetPath: storage.trace.s3.access_key
      kind: Secret
      name: tempo-op
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: storage.trace.s3.secret_key
      kind: Secret
      name: tempo-op
      valuesKey: AWS_SECRET_ACCESS_KEY
