configStorageType: Secret
storage:
  trace:
    backend: s3
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
ingester:
  replicas: 2
  podLabels:
    grafana-agent/collect-metrics: "true"
memcached:
  enabled: false
minio:
  enabled: false
