configStorageType: Secret
storage:
  trace:
    backend: s3
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
compactor:
  replicas: 3
distributor:
  replicas: 3
ingester:
  replicas: 3
querier:
  replicas: 3
query_frontend:
  replicas: 3
memcached:
  enabled: false
minio:
  enabled: false
