apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: networking
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/part-of: tailscale
spec:
  # This can never be higher than 1 since sharing an authentication key does not work.
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/part-of: tailscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.40.1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-op
                  key: TS_AUTH_KEY
            - name: TS_KUBE_SECRET
              value: tailscale-state
            - name: TS_DEST_IP
              value: 10.96.0.60
            - name: TS_EXTRA_ARGS
              value: --hostname=liveview-template-app
