apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - secretKey: TS_AUTH_KEY
      remoteRef:
        key: networking-tailscale
        property: TS_AUTH_KEY
