apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      chart: cert-manager
      version: v1.12.17
  interval: 10m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
