apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-main-rw
spec:
  cluster:
    name: postgresql-main

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
