apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  dataFrom:
    - extract:
        key: hcloud
