vpa:
  enabled: true
dashboard:
  replicaCount: 1
  ingress:
    enabled: true
    ingressClassName: private
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: liveview-template-app.manticore-hippocampus.ts.net
      ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: &host goldilocks.liveview-template.app
        paths:
          - path: /
            type: Prefix
    tls:
      - secretName: goldilocks-tls
        hosts:
          - *host

