apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://opensearch-cluster-master.database.svc.cluster.local:9200
        index-prefix: jaeger
        secretName: opensearch-creds
        tls:
          ca: /os/certificates/ca.crt
  volumes:
    - name: opensearch-tls
      secret:
        secretName: opensearch-tls
  volumeMounts:
    - name: opensearch-tls
      mountPath: /os/certificates/
      readOnly: true
