k8sServiceHost: cluster.liveview-template.app
k8sServicePort: 6443
ipam:
  mode: kubernetes
kubeProxyReplacement: disabled
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
securityContext:
  privileged: false
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    mountCgroup:
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    applySysctlOverwrites:
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
# ---
# autoDirectNodeRoutes: false
# endpointRoutes:
#   enabled: true
# loadBalancer:
#   algorithm: maglev
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
operator:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA,
      - drop
      - tcp
      - flow
      - http
      - icmp
      - port-distribution
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
    replicas: 3
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      className: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: liveview-template-app.manticore-hippocampus.ts.net
        ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - &host hubble.liveview-template.app
      tls:
        - secretName: hubble-tls
          hosts:
            - *host
