apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: jaeger-operator
      version: 2.43.0
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
