apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      chart: external-dns
      version: 1.12.2
  interval: 10m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
