apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-flux-system
  namespace: flux-system
spec:
  dependsOn:
    - name: services-kube-system-external-secrets-stores
  path: ./kubernetes/services/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: liveview-template
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 3m
