apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour-private
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 11.3.0
      chart: contour-private
  interval: 30m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: contour-private-values
