contour:
  # We are deploying Contour twice - having both deployments manage the CRDs
  # fails. This release is the one managing CRDs.
  manageCRDs: true
  ingressClass:
    name: private
    default: true
envoy:
  service:
    type: ClusterIP
    externalTrafficPolicy: ''
    clusterIP: 10.96.0.60
