contour:
  # We are deploying Contour twice - having both deployments manage the CRDs
  # fails. This release is the one managing CRDs.
  manageCRDs: true
  ingressClass:
    name: private
    default: true
envoy:
  sideCars:
    - name: tailscale
      image: ghcr.io/tailscale/tailscale:v1.40.0
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      env:
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale
              key: TS_AUTH_KEY
        - name: TS_KUBE_SECRET
          value: tailscale-state
        - name: TS_EXTRA_ARGS
          value: --hostname=liveview-template-app
