apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-timezone
  annotations:
    policies.kyverno.io/title: Inject timezone
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy injects an initContainer to Pods to set up TZ
      environment variable so the container will have the correct
      time.
spec:
  generateExisting: true
  rules:
    - name: inject-timezone
      match:
        any:
          - resources:
              kinds:
                - Pod
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: set-timezone
                image: quay.io/k8tz/k8tz:0.13.0
                args:
                  - bootstrap
                volumeMounts:
                  - name: timezone
                    mountPath: /mnt/zoneinfo
            containers:
              - (name): "*"
                volumeMounts:
                  - name: timezone
                    mountPath: /etc/localtime
                    subPath: &timezone Europe/Berlin
                    readOnly: true
                  - name: timezone
                    mountPath: /usr/share/zoneinfo
                    readOnly: true
                env:
                  - name: TZ
                    value: *timezone
            volumes:
              - name: timezone
                emptyDir: {}
