apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kratos-op
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      engineVersion: v2
      data:
        DATABASE_HOST: &host "{{ .DATABASE_HOST }}"
        DATABASE_USER: &user "{{ .DATABASE_USER }}"
        DATABASE_PASSWORD: &pass "{{ .DATABASE_PASSWORD }}"
        DATABASE_NAME: &name "{{ .DATABASE_NAME }}"
        dsn: "postgres://{{ .DATABASE_USER }}:{{ .DATABASE_PASSWORD }}@{{ .DATABASE_HOST }}:5432/{{ .DATABASE_NAME }}"
        secretsDefault: "{{ .DEFAULT_SECRETS }}"
        secretsCookie: "{{ .COOKIE_SECRETS }}"
        secretsCipher: "{{ .CIPHER_SECRETS }}"
        smtpConnectionURI: "{{ .SMTP_URL }}"
        # init-db
        POSTGRES_HOST: *host
        POSTGRES_SUPERUSER: "{{ .SUPERUSER }}"
        POSTGRES_SUPERUSER_PASSWORD: "{{ .SUPERUSER_PASSWORD }}"
        POSTGRES_USER: *user
        POSTGRES_PASSWORD: *pass
        POSTGRES_DB: *name
  dataFrom:
    - extract:
        key: kratos
    - extract:
        key: postgresql-main
