imagePullSecrets:
  - name: dockerconfigjson-github
replicaCount: 3
kratos:
  automigration:
    enabled: true
deployment:
  extraEnv:
    - name: COURIER_SMTP_CONNECTION_URI
      valueFrom:
        secretKeyRef:
          name: {{ include "kratos.secretname" . }}
          key: smtpConnectionURI
job:
  extraInitContainers: |
    - name: init-db
      image: ghcr.io/cschmatzler/postgresql-initdb:15.2
      imagePullPolicy: Always
      envFrom:
        - secretRef:
            name: kratos-op
secret:
  enabled: false
  nameOverride: kratos-op
