imagePullSecrets:
  - name: dockerconfigjson-github
replicaCount: 3
kratos:
  automigration:
    enabled: true
  config:
    selfservice:
      default_browser_return_url: "https://kratos.liveview-template.app/"
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
  identitySchemas:
    "identity.default.schema.json": |
      {
         "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
         "$schema": "http://json-schema.org/draft-07/schema#",
         "title": "Person",
         "type": "object",
         "properties": {
            "traits": {
               "type": "object",
               "properties": {
                  "email": {
                     "type": "string",
                     "format": "email",
                     "title": "E-Mail",
                     "ory.sh/kratos": {
                        "credentials": {
                           "password": {
                              "identifier": true
                           }
                        },
                        "recovery": {
                           "via": "email"
                        },
                        "verification": {
                           "via": "email"
                        }
                     }
                  }
               },
               "required": [
                  "email"
               ],
               "additionalProperties": false
            }
         }
      }
deployment:
  extraEnv:
    - name: COURIER_SMTP_CONNECTION_URI
      valueFrom:
        secretKeyRef:
          name: kratos-op
          key: SMTP_URL
job:
  extraInitContainers: |
    - name: init-db
      image: ghcr.io/cschmatzler/postgresql-initdb:15.2
      imagePullPolicy: Always
      envFrom:
        - secretRef:
            name: kratos-op
secret:
  enabled: false
  nameOverride: kratos-op
ingress:
  public:
    enabled: true
    ingressClassName: public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: &host kratos.liveview-template.app
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: kratos-tls
        hosts:
          - *host
