apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://opensearch-cluster-master.database.svc.cluster.local:9200
        index-prefix: jaeger
