apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    replicaCount: 1
    serviceMonitor:
      enabled: true
    webhook:
      replicaCount: 3
      serviceMonitor:
        enabled: true
    certController:
      replicaCount: 3
      serviceMonitor:
        enabled: true
