apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/services
  prune: true
  sourceRef:
    kind: GitRepository
    name: liveview-template
