apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      chart: mimir
      version: 4.4.0-weekly.236
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
