mimir:
  structuredConfig:
    common:
      ring:
        kvstore:
          store: memberlist
      path_prefix: /var/loki
      storage:
        backend: s3
    memberlist:
      join_members:
        - mimir-memberlist.monitoring.svc.cluster.local
minio:
  enabled: false
blocks_storage:
  s3:
    bucket_name: mimir-blocks
alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager
ruler_storage:
  s3:
    bucket_name: mimir-ruler
distributor:
  replicas: 2
ingester:
  replicas: 2
querier:
  replicas: 1
query_frontend:
  replicas: 1
ruler:
  replicas: 1
store_gateway:
  replicas: 2
nginx:
  replicas: 1
