configStorageType: Secret
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
    blocks_storage:
      s3:
        bucket_name: liveview-template-app-mimir-blocks
    alertmanager_storage:
      s3:
        bucket_name: liveview-template-app-mimir-alertmanager
    ruler_storage:
      s3:
        bucket_name: liveview-template-app-mimir-ruler
distributor:
  replicas: 1
ingester:
  replicas: 2
  zoneAwareReplication:
    enabled: false
querier:
  replicas: 2
query_scheduler:
  replicas: 1
query_frontend:
  replicas: 1
ruler:
  replicas: 1
store_gateway:
  replicas: 2
  zoneAwareReplication:
    enabled: false
overrides_exporter:
  enabled: false
nginx:
  enabled: false
rollout_operator:
  enabled: false
minio:
  enabled: false
