configStorageType: Secret
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
    blocks_storage:
      s3:
        bucket_name: liveview-template-app-mimir
distributor:
  replicas: 3
  resources:
    requests:
      cpu: 128m
      memory: 768M
    limits:
      memory: 768M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
ingester:
  replicas: 3
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 128m
      memory: 768M
    limits:
      memory: 768M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
querier:
  replicas: 3
  resources:
    requests:
      cpu: 32m
      memory: 128M
    limits:
      memory: 128M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
query_scheduler:
  replicas: 3
  resources:
    requests:
      cpu: 16m
      memory: 128M
    limits:
      memory: 128M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
query_frontend:
  replicas: 3
  resources:
    requests:
      cpu: 16m
      memory: 128M
    limits:
      memory: 128M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
store_gateway:
  replicas: 3
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 32m
      memory: 128M
    limits:
      memory: 128M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
compactor:
  replicas: 3
  resources:
    requests:
      cpu: 32m
      memory: 256M
    limits:
      memory: 256M
  service:
    labels:
      grafana-agent/collect-metrics: "true"
overrides_exporter:
  enabled: false
ruler:
  enabled: false
alertmanager:
  enabled: false
nginx:
  enabled: false
rollout_operator:
  enabled: false
minio:
  enabled: false
