apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workloads
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: liveview-template
