apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-tls
spec:
  secretName: opensearch-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  commonName: opensearch.liveview-template.app
  dnsNames:
    - opensearch.liveview-template.app
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
