apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-tls
spec:
  secretName: opensearch-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: opensearch.liveview-template.app
  dnsNames:
    - opensearch.liveview-template.app
    - opensearch-cluster-master.database.svc.cluster.local
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "monitoring"
