controller:
  type: deployment
  replicas: 2
agent:
  configMap:
    create: false
    name: grafana-agent-traces-config
    key: config.river
  extraPorts:
    - name: otlp-http
      port: 4318
      targetPort: 4318
