apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: ingress-nginx-private-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
