apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller-private
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      chart: nginx-ingress-controller
      version: 9.5.1
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: nginx-ingress-controller-private-values
