apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  labels:
    app.kubernetes.io/part-of: cert-manager
spec:
  acme:
    email: admin@liveview-template.app
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: security-cert-manager
              key: CF_API_TOKEN
