apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: liveview-template
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/cschmatzler/liveview-template
  ref:
    branch: master
  secretRef:
    name: github-deploy-key
  ignore: |
    /*
    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: liveview-template
  namespace: flux-system
spec:
  interval: 30s
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: liveview-template
