apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.security.svc.cluster.local:8080
      vaults:
        liveview-template: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-credentials
            namespace: kube-system
            key: token
