apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: networking
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/part-of: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/part-of: tailscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: tailscale
    spec:
      serviceAccountName: tailscale
      initContainers:
          # In order to run as a proxy we need to enable IP Forwarding inside
          # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
          # in Kubelet by default.
        - name: sysctler
          image: busybox
          securityContext:
            privileged: true
          command:
            - /bin/sh
          args:
            - -c
            - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.40.0
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: TS_AUTH_KEY
            - name: TS_KUBE_SECRET
              value: tailscale-state
            - name: TS_DEST_IP
              value: 10.96.0.60
            - name: TS_EXTRA_ARGS
              value: --hostname=liveview-template-app
