contour:
  # We are deploying Contour twice - having both deployments manage the CRDs
  # fails. We will let the `contour-public` deployment handle these.
  manageCRDs: false
  ingressClass:
    name: private
    default: true
envoy:
  useHostPort: false
  service:
    type: ClusterIP
    externalTrafficPolicy: ""
    clusterIP: 10.96.0.60
