apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator
        namespace: flux-system
      version: 1.9.0
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: liveview-template-cluster
  namespace: postgres-operator
  labels:
    team: acid
spec:
  teamId: "acid"
  volume:
    size: 10Gi
  numberOfInstances: 3
  postgresql:
    version: "15"
  enableConnectionPooler: true
  preparedDatabases:
    liveview_template:
      defaultUsers: true
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      memory: 500Mi
  connectionPooler:
     resources:
       requests:
         cpu: 100m
         memory: 250Mi
       limits:
         memory: 250Mi
