apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      chart: cloudnative-pg
      version: 0.17.1
  interval: 1h
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 3
