ingressClassResource:
  name: public
controller:
  replicaCount: 2
defaultBackend:
  replicaCount: 2
service:
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/type: lb11
    load-balancer.hetzner.cloud/use-private-ip: "true"
