apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-ccm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:ccm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hcloud-ccm
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-ccm
  namespace: kube-system
  labels:
    app.kubernetes.io/name: hcloud-ccm
    app.kubernetes.io/part-of: hcloud-ccm
    app.kubernetes.io/version: 1.15.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hcloud-ccm
      app.kubernetes.io/part-of: hcloud-ccm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hcloud-ccm
        app.kubernetes.io/part-of: hcloud-ccm
        app.kubernetes.io/version: 1.15.0
    spec:
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
          operator: Exists
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
      serviceAccountName: hcloud-ccm
      hostNetwork: true
      dnsPolicy: Default
      containers:
        - name: hcloud-ccm
          image: hetznercloud/hcloud-cloud-controller-manager:v1.15.0
          command:
            - "/bin/hcloud-cloud-controller-manager"
            - "--allow-untagged-cloud"
            - "--cloud-provider=hcloud"
            - "--leader-elect=false"
            - "--route-reconciliation-period=30s"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hcloud
                  key: token
