apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator
        namespace: flux-system
      version: 1.9.0
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: postgres-operator-ui
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator-ui
        namespace: flux-system
      version: 1.9.0
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: liveview-template-cluster
spec:
  teamId: "acid"
  volume:
    size: 10Gi
  numberOfInstances: 3
  postgresql:
    version: "15"
  preparedDatabases:
    liveview_template:
      defaultUsers: true
