apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services-monitoring-jaeger-operator
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: liveview-template
  path: ./kubernetes/services/monitoring/jaeger-operator/service
  interval: 15m
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jaeger-operator
      namespace: monitoring
