apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack.yaml
  - ./thanos/kustomization.yaml
  - ./loki/kustomization.yaml
  - ./vector/kustomization.yaml
  - ./grafana/kustomization.yaml
