apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services-monitoring-loki
  namespace: flux-system
spec:
  dependsOn:
    - name: services-kube-system-external-secrets-stores
  sourceRef:
    kind: GitRepository
    name: liveview-template
  path: ./kubernetes/services/monitoring/loki
  interval: 15m
  timeout: 5m
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: loki
      namespace: monitoring
