name: Test and analyze app
on:
  pull_request:

jobs:
  check:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.7.4

      - name: Log into GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run earthly +ci
        run: earthly -P --ci --push --output --use-inline-cache --save-inline-cache +ci

      - name: Upload to Codecov
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3
        with:
          os: aarch64
          token: ${{ secrets.CODECOV_TOKEN }}
          files: excoveralls-report.json
