name: Deploy app
on:
  push:
    branches:
      - master
    paths-ignore:
      - infra/
      - k8s/

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.7.4

      - name: Log into GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment
        run: echo "VERSION=$(date '+%y.%-m.%-d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Run Earthly +prod-image
        run: earthly --ci --push --build-arg IMAGE_TAG=$VERSION +prod-image

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - run: echo "VERSION=$(date '+%y.%-m.%-d')-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: git config --global user.name "actions[bot]"
      - run: git config --global user.email "actions@liveview-template.app"
      - run: echo $VERSION > version
      - run: git tag -a $VERSION -m "Release $VERSION"
      - run: git push --tags
      - run: git commit -am "Release $VERSION"
      - run: git push
