name: Check
on:
  pull_request:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  MIX_ENV: test

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        id: deps-cache
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix compile --warnings-as-errors

  test:
    runs-on: ubuntu-latest
    needs: compile
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix ecto.reset
      - run: mix coveralls.json
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover/excoveralls.json

  lint:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.unlock --check-unused
      - run: mix hex.audit
      - run: mix format --check-formatted
      - run: mix credo
      - run: mix excellent_migrations.check_safety
      - run: mix sobelow --config
      - uses: aquasecurity/trivy-action@v0.9.2
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
