name: Check
on:
  push:
  pull_request:

env:
  MIX_ENV: test

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            deps
            _build

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: mix ecto.reset
      - run: mix coveralls.json
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover/excoveralls.json
