name: Check
on:
  push:
  pull_request:

env:
  MIX_ENV: test

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        id: compile-cache
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
        if: steps.compile-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        if: steps.compile-cache.outputs.cache-hit != 'true'
      - run: mix compile

  test:
    runs-on: ubuntu-latest
    needs: compile
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-$GITHUB_SHA
          restore-keys: |
            mix-
      - run: mix ecto.reset
      - run: mix coveralls.json
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover/excoveralls.json

  lint:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-$GITHUB_SHA
          restore-keys: |
            mix-
      - run: mix format --check-formatted
      - run: mix credo --strict

  analysis:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14-otp-25"
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-$GITHUB_SHA
          restore-keys: |
            mix-
      - run: mix sobelow --config
