name: "Kubernetes: Rebuild images"

on:
  push:
    branches:
      - master
    # paths:
    #   - "kubernetes/images/**"

jobs:
  collect-changes:
    name: Collect changes
    runs-on: ubuntu-latest
    outputs:
      addedOrModifiedImages: ${{ steps.collect-images.outputs.addedOrModifiedImages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Collect changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            addedOrModified:
              - added|modified: 'kubernetes/images/**'

      - name: Collect changed images
        id: collect-images
        if: |
          steps.filter.outputs.addedOrModified == 'true'
        shell: bash
        run: |
          PATHS='${{ steps.filter.outputs.addedOrModified_files }}'
          OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/")[2]) | unique')
          echo "addedOrModifiedImages=${OUTPUT}" >> $GITHUB_OUTPUT

  build-images:
    name: Build images
    uses: ./.github/workflows/build-images.yaml
    needs:
      - collect-changes
    with:
      images: "${{ needs.collect-changes.outputs.addedOrModifiedImages }}"
