name: Release
on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "$(date '+%y.%m.%d')-$GITHUB_SHA" > version
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@medium.place"
          git commit -am "Bump version"
          git push

  sentry:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v2
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: prod
