name: Release
on:
  push:
    branches:
      - master

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=$(date '+%y.%-m.%-d')-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: git tag -a $VERSION -m "Release $VERSION"
      - run: |
          git config --global user.name "actions[bot]"
          git config --global user.email "actions@medium.place"
          git push
