name: "Template: Check"
on:
  pull_request:
    paths-ignore:
      - infra/
      - k8s/
env:
  MIX_ENV: test
jobs:
  compile:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: erlef/setup-beam@c2e02f777c158310fc6d3d4e11b36a52d2d52db8 # v1
        with:
          otp-version: "26.0"
          elixir-version: "1.14.4-otp-26"
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: deps-cache
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-
      - run: mix deps.get
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix compile --warnings-as-errors

  test:
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: compile
    env:
      POSTGRES_HOST: localhost
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: erlef/setup-beam@c2e02f777c158310fc6d3d4e11b36a52d2d52db8 # v1
        with:
          otp-version: "26.0"
          elixir-version: "1.14.4-otp-26"
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            deps
            _build
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix ecto.drop
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix coveralls.json
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover/excoveralls.json

  analyze:
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: compile
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: erlef/setup-beam@c2e02f777c158310fc6d3d4e11b36a52d2d52db8 # v1
        with:
          otp-version: "26.0"
          elixir-version: "1.14.4-otp-26"
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            deps
            _build
          key: mix-${{ github.sha }}
          restore-keys: |
            mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.unlock --check-unused
      - run: mix hex.audit
      - run: mix format --check-formatted
      - run: mix credo
      - run: mix excellent_migrations.check_safety
      - run: mix sobelow --config
