apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      chart: grafana-agent
      version: 0.13.0
  interval: 10m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: grafana-agent-values
