apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: grafana-agent-values
    files:
      - values.yaml=./values.yaml
  - name: grafana-agent-config
    files:
      - config.river=./config.river
    options:
      disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
